//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sites
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ListSites { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
    }
}
